### ISSUE TITLE
meta.NEXT_MINOR_VERSION is not populated in PATTERN strategy

### ISSUE THREAD

**Issue by athlan** [jgitver/jgitver-maven-plugin#138]
## Issue

**version**: 1.5.1

**usage context**:

- [x] maven command line: 3.6.1 
- [ ] eclipse: _not applicable_
- [ ] netbeans: _not applicable_
- [ ] Intellij IDEA: _not applicable_

**Problem description**:

I would like to use PATTERN strategy in order to parametrize how versions are bumped. Following instructions: https://jgitver.github.io/#_modes I've created the following config file:
```
<configuration xmlns="http://jgitver.github.io/maven/configuration/1.1.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://jgitver.github.io/maven/configuration/1.1.0 https://jgitver.github.io/maven/configuration/jgitver-configuration-v1_1_0.xsd">
    <strategy>PATTERN</strategy>
    <autoIncrementPatch>true</autoIncrementPatch>
    <versionPattern>${M}.${&lt;meta.NEXT_MINOR_VERSION}.${p}</versionPattern>
</configuration>
```

However, metadata is not resolved properly (does not indicates next bumped minor version as per documentation says).
![image](https://user-images.githubusercontent.com/2697638/89867791-ff787480-dbb1-11ea-85f1-e4833c9ca8f5.png)

Instead, I'm getting the following error:
```
mvn validate
[INFO] Using jgitver configuration file: C:\Dev\Repos\tmp\demo-maven-releases\.mvn\jgitver.config.xml
[INFO] Using jgitver-maven-plugin [1.5.1] (sha1: e45d1669b39cedb98720dd33cc14d0185b455ca1)
[WARNING] cannot autoclose GitVersionCalculator object for project: C:\Dev\Repos\tmp\demo-maven-releases
java.lang.IllegalStateException: failure calculating version
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.buildVersion (GitVersionCalculatorImpl.java:349)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.computeVersion (GitVersionCalculatorImpl.java:163)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject (GitVersionCalculatorImpl.java:180)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject (GitVersionCalculatorImpl.java:174)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion (GitVersionCalculatorImpl.java:267)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion (GitVersionCalculatorImpl.java:262)
    at fr.brouillard.oss.jgitver.JGitverExtension.afterSessionStart (JGitverExtension.java:114)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:208)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: fr.brouillard.oss.jgitver.impl.VersionCalculationException: cannot compute version
    at fr.brouillard.oss.jgitver.impl.PatternVersionStrategy.build (PatternVersionStrategy.java:116)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.buildVersion (GitVersionCalculatorImpl.java:340)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.computeVersion (GitVersionCalculatorImpl.java:163)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject (GitVersionCalculatorImpl.java:180)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject (GitVersionCalculatorImpl.java:174)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion (GitVersionCalculatorImpl.java:267)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion (GitVersionCalculatorImpl.java:262)
    at fr.brouillard.oss.jgitver.JGitverExtension.afterSessionStart (JGitverExtension.java:114)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:208)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.IllegalStateException: cannot parse 0..2 as a semver compatible version
    at fr.brouillard.oss.jgitver.Version.parse (Version.java:153)
    at fr.brouillard.oss.jgitver.impl.pattern.VersionPatternGrammarDefinition.lambda$new$0 (VersionPatternGrammarDefinition.java:52)
    at org.petitparser.parser.actions.ActionParser.parseOn (ActionParser.java:31)
    at org.petitparser.parser.combinators.EndOfInputParser.parseOn (EndOfInputParser.java:23)
    at org.petitparser.parser.combinators.DelegateParser.parseOn (DelegateParser.java:24)
    at fr.brouillard.oss.jgitver.impl.pattern.VersionGrammarParser.parseOn (VersionGrammarParser.java:41)
    at org.petitparser.parser.Parser.parse (Parser.java:49)
    at fr.brouillard.oss.jgitver.impl.PatternVersionStrategy.build (PatternVersionStrategy.java:105)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.buildVersion (GitVersionCalculatorImpl.java:340)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.computeVersion (GitVersionCalculatorImpl.java:163)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject (GitVersionCalculatorImpl.java:180)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject (GitVersionCalculatorImpl.java:174)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion (GitVersionCalculatorImpl.java:267)
    at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion (GitVersionCalculatorImpl.java:262)
    at fr.brouillard.oss.jgitver.JGitverExtension.afterSessionStart (JGitverExtension.java:114)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:208)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Scanning for projects...

```
